#!/usr/bin/perl -w
use strict;
use feature qw(say);
use autodie;
use utf8;
binmode(STDOUT, ":utf8");
use Storable;
my $Storable_file = 'CRE_info_hash';

my %CRE = %{retrieve $Storable_file};

my %duration;
for my $key (keys %CRE) {
	my $duration = $CRE{$key}{'duration'};
	$duration =~ s/://g;
	push @{$duration{$duration}}, $key; ## $duration is not unique
}

my $count = 0;
for my $duration (sort { $b <=> $a } keys %duration) {
	$count++;
	(my $duration_human_readable = $duration) =~ s/(\d{2})(\d{2})(\d{2})/$1:$2:$3/;
	my $CRE_eps = join "\t", map $CRE{$_}{'title'}, @{$duration{$duration}}; ## 
	printf "Rank %03d with %s: %s\n", $count, $duration_human_readable, $CRE_eps;
}
